apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: event-listener
  name: event-listener
spec:
  containers:
  - image: ghcr.io/khachatur-s/event-simulator:latest
    name: event-listener
