name: Build PROD image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/khachatur-s/event-simulator:latest
        docker push ghcr.io/khachatur-s/event-simulator:latest